### User Registration
POST http://localhost:3000/api/v1/auth/sign-up
Content-Type: application/json

{
  "name": "Anandita Sharma",
  "email": "ananditasharma2024@gmail.com",
  "password": "anandita_sharma"
}

###user login
POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "ananditasharma2024@gmail.com",
  "password": "anandita_sharma"
}


### Create subscription
POST http://localhost:3000/api/v1/subscriptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTA1YWVmOWM0NjI3MjBiZDQyODc3YWYiLCJpYXQiOjE3NjMzOTY4MDYsImV4cCI6MTc2MzQ4MzIwNn0.RH9ItkSliySXiIB_OiIJqTx7nYxQoDh9vNYpE3iYeSs
Content-Type: application/json

{
  "name": "YouTube",
  "price": 199,
  "currency": "INR",
  "frequency": "monthly",
  "category": "entertainment",
  "paymentMethod": "debit_card",
  "startDate": "2025-10-20"
}

### update subscription
PUT http://localhost:3000/api/v1/subscriptions/691b47133f484ab3e4230f15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTA1YWVmOWM0NjI3MjBiZDQyODc3YWYiLCJpYXQiOjE3NjMzOTUxMDIsImV4cCI6MTc2MzQ4MTUwMn0.exUDfbrwh11uldyeipZNK6lQ2hFO2So_J2VC402CwWE
Content-Type: application/json

{
  "price": 299,
  "paymentMethod": "credit_card"
}

### get subscription by user id
GET http://localhost:3000/api/v1/subscriptions/user/6905aef9c462720bd42877af
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTA1YWVmOWM0NjI3MjBiZDQyODc3YWYiLCJpYXQiOjE3NjMzOTUxMDIsImV4cCI6MTc2MzQ4MTUwMn0.exUDfbrwh11uldyeipZNK6lQ2hFO2So_J2VC402CwWE

### get subscription by id
GET http://localhost:3000/api/v1/subscriptions/691b47133f484ab3e4230f15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTA1YWVmOWM0NjI3MjBiZDQyODc3YWYiLCJpYXQiOjE3NjMzOTUxMDIsImV4cCI6MTc2MzQ4MTUwMn0.exUDfbrwh11uldyeipZNK6lQ2hFO2So_J2VC402CwWE


### delete subscription
DELETE http://localhost:3000/api/v1/subscriptions?id=6905afdd5555ba6f69abf280
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTA1YWVmOWM0NjI3MjBiZDQyODc3YWYiLCJpYXQiOjE3NjE5ODAzNTgsImV4cCI6MTc2MjA2Njc1OH0.1TmM7bZ-0wXEnWyi2kXNBHBBENLDZRjHZX3mQgZF6NU


### signup
POST http://localhost:3000/api/v1/auth/sign-up
Content-Type: application/json

{
  "name": "Anandita Sharma",
  "email": "221210018@nitdelhi.ac.in",
  "password": "admin123"
}

### get all users
GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGJkOGVlZWFkZDY2MGY2NjIwOGNjNmQiLCJpYXQiOjE3NTcyNTMzNTgsImV4cCI6MTc1NzMzOTc1OH0.THQ_t_Aw8BvJprV64TcVxnNfBOLM633Z-rc8H6BwDM8

###get user by id
GET http://localhost:3000/api/v1/users/68bb0f119b9373758be0c45a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGJkOGVlZWFkZDY2MGY2NjIwOGNjNmQiLCJpYXQiOjE3NTcyNTMzNTgsImV4cCI6MTc1NzMzOTc1OH0.THQ_t_Aw8BvJprV64TcVxnNfBOLM633Z-rc8H6BwDM8



###user login
POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "221210018@nit.ac.in",
  "password": "admin123"
}

### update user
PUT http://localhost:3000/api/v1/users/68bd969cdc61335c1ddb2397
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGJkOTY5Y2RjNjEzMzVjMWRkYjIzOTciLCJpYXQiOjE3NTcyNTU1MTksImV4cCI6MTc1NzM0MTkxOX0.xVSHoMeepbP-c2PaUEBIFhXn7akIPWcaRS_-cmdwJj0
Content-Type: application/json

{
  "name": "Admin Updated",
  "email": "221210018@nit.ac.in"
}

### delete user
DELETE http://localhost:3000/api/v1/users/68bd969cdc61335c1ddb2397
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGJkOTY5Y2RjNjEzMzVjMWRkYjIzOTciLCJpYXQiOjE3NTcyNTU1MTksImV4cCI6MTc1NzM0MTkxOX0.xVSHoMeepbP-c2PaUEBIFhXn7akIPWcaRS_-cmdwJj0

### get all subscriptions

GET http://localhost:3000/api/v1/subscriptions
Authorization: Bearer <JWT_TOKEN>


### create subscription
POST http://localhost:3000/api/v1/subscriptions
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "name": "Netflix Premium",
  "price": 999,
  "currency": "INR",
  "frequency": "monthly",
  "category": "entertainment",
  "paymentMethod": "debit_card",
  "startDate": "2025-08-13"
}

### create admin
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "221210018@nit.ac.in",
  "password": "admin123"
}


### cancel subscription
PUT http://localhost:3000/api/v1/subscriptions/SUBSCRIPTION_ID/cancel
Authorization: Bearer <JWT_TOKEN>

### get upcoming renewals
GET http://localhost:3000/api/v1/subscriptions/upcoming-renewals
Authorization: Bearer <JWT_TOKEN>
