### User Registration
POST http://localhost:3000/api/v1/auth/sign-up
Content-Type: application/json

{
  "name": "Anandita Sharma",
  "email": "aananditasharma2003@gmail.com",
  "password": "ananditasharma"
}

###user login
POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "aananditasharma2003@gmail.com",
  "password": "ananditasharma"
}


### Create subscription
POST http://localhost:3000/api/v1/subscriptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGJiMGYxMTliOTM3Mzc1OGJlMGM0NWEiLCJpYXQiOjE3NTcwOTU0MDQsImV4cCI6MTc1NzE4MTgwNH0.1kveTqijBZzmxL3rMR4b4kJGWalLY1FTewoIfLTPAPE
Content-Type: application/json

{
  "name": "Netflix Premium",
  "price": 999,
  "currency": "INR",
  "frequency": "monthly",
  "category": "entertainment",
  "paymentMethod": "debit_card",
  "startDate": "2025-08-13"
}
